name: Encode-Newlines
version: 0.02
abstract: Normalize line ending sequences
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  perl: 5.7.3
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
